### PR TITLE
Prerequisites updated

### LINKED ISSUE #1398: Prerequisites page should auto-detect system requirements
## Description

At the moment when the Prerequisites page opens, it will ask the user to confirm they have at least 4GB of RAM.

We should attempt to automatically detect this ourselves.
## Possible Fix

Try to determine whether a user has at least 4GB of RAM
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by kemi04**
Signed-off-by: Kestutis Gudynas <44440041+kemi04@users.noreply.github.com>
Closes #1398

### CODE REVIEW

File: packages/blockchain-extension/extension/dependencies/DependencyManager.ts [hunk 1]
```diff
@@ -238,13 +238,13 @@ export class DependencyManager {
             if (composeVersion) {
                 dependencies.dockerCompose.version = composeVersion;
             }
+            const os = require('os');
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/extension/dependencies/DependencyManager.ts:241]: As a general rule, it's best to do all the imports at the top of the file

File: packages/blockchain-extension/test/dependencies/DependencyManager.test.ts [hunk 2]
```diff
@@ -1746,6 +1746,8 @@ describe('DependencyManager Tests', () => {
         let sendCommandStub: sinon.SinonStub;
         let extensionData: ExtensionData;
         let dependencyManager: DependencyManager;
+        const os: any = require('os');
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/test/dependencies/DependencyManager.test.ts:1749]: Best move the import to the top

File: packages/blockchain-extension/test/dependencies/DependencyManager.test.ts [hunk 3]
```diff
@@ -2034,6 +2064,7 @@ describe('DependencyManager Tests', () => {
 
             const result: any = await dependencyManager.getPreReqVersions();
             should.not.exist(result.javaTestRunnerExtension.version);
+            totalmemStub.should.have.been.calledOnce;
         });
 
         it('should return true if user has agreed to system requirements', async () => {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/test/dependencies/DependencyManager.test.ts:2070]: Should probably change the name of the test now

File: packages/blockchain-extension/test/dependencies/DependencyManager.test.ts [hunk 4]
```diff
@@ -2043,28 +2074,30 @@ describe('DependencyManager Tests', () => {
...
             newExtensionData.version = currentExtensionVersion;
             newExtensionData.generatorVersion = extDeps['generator-fabric'];
             await GlobalState.update(newExtensionData);
 
             const result: any = await dependencyManager.getPreReqVersions();
             result.systemRequirements.complete.should.equal(true);
+            totalmemStub.should.have.been.calledOnce;
         });
 
         it(`should return false if user hasn't agreed to system requirements`, async () => {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/test/dependencies/DependencyManager.test.ts:2086]: Should probably change this test name as well
