### PR TITLE
Fixed JS debug with TS tests (close #480)

### LINKED ISSUE #480: debug fails for javascript smart contract if typescript test file is found in workspace
Debug searches for typescript files and is expecting a typescript project if it finds one, which could be a test file, which you can generate through the extension

### PR DESCRIPTION
**Pull request by Jakeeyturner**
Signed-off-by: Jake Turner <jaketurner25@live.com>

### CODE REVIEW

File: client/src/debug/FabricDebugConfigurationProvider.ts [hunk 1]
```diff
@@ -81,7 +81,12 @@ export class FabricDebugConfigurationProvider implements vscode.DebugConfigurati
                 config.program = path.join(folder.uri.fsPath, 'node_modules', '.bin', 'fabric-chaincode-node');
             }
 
-            const tsFiles: Array<vscode.Uri> = await vscode.workspace.findFiles(new vscode.RelativePattern(folder, '**/*.ts'), '**/node_modules/**', 1);
+            const allTsFiles: Array<vscode.Uri> = await vscode.workspace.findFiles(new vscode.RelativePattern(folder, '**/*.ts'), '**/node_modules/**', 1);
+
+            // Ignore any TypeScript test files in a JavaScript project
+            const tsFiles: Array<vscode.Uri> = allTsFiles.filter((file: vscode.Uri) => {
+                return !file.fsPath.endsWith('.test.ts');
```
Comment (sstone1) [inline client/src/debug/FabricDebugConfigurationProvider.ts]: Isn't this a naming convention rather than actually being required?

Comment (Jakeeyturner) [reply client/src/debug/FabricDebugConfigurationProvider.ts]: It would've picked up on our generated tests, but to be safe we'll now search for a `tsconfig.json` before assuming a project is TypeScript.
