### PR TITLE
Refresh panels every 60 seconds (close #1879)

### LINKED ISSUE #1879: Periodically refresh gateways, wallets and environments panels
## Description

We should periodically refresh these panels in order to check if anything else should be in the tree.
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by Jakeeyturner**
Signed-off-by: Jake Turner <jaketurner25@live.com>

### CODE REVIEW

File: packages/blockchain-extension/extension/util/ExtensionUtil.ts [hunk 1]
```diff
@@ -556,6 +556,15 @@ export class ExtensionUtil {
             }
         });
 
+        if (!process.env.REFRESH_PANELS || process.env.REFRESH_PANELS === 'true') {
+            setInterval(() => {
```
Comment (cazfletch) [inline packages/blockchain-extension/extension/util/ExtensionUtil.ts]: can you not reuse the set interval function we have already

Comment (Jakeeyturner) [reply packages/blockchain-extension/extension/util/ExtensionUtil.ts]: Updated to use the TimerUtil.setInterval function - had to change it to handle multiple sets of commands and arguments.
