### PR TITLE
Use the caName option in connection-config when enrolling (close #1345)

### LINKED ISSUE #1345: Add Identity failed when there is "caName" in "connection-profile"
## Description
The Add Identity command ignores the caName option in the connection-profile, so enroll fails.

## Expected Behavior
enroll success

## Actual Behavior
Error Message:
Unable to add identity to wallet: Enrollment failed with errors [[{"code":20,"message":"Authentication failure"}]]

## Possible Fix
Read and use the caName option in the connection-profile.

## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by mazyblue**

### CODE REVIEW

File: src/commands/addWalletIdentityCommand.ts [hunk 1]
```diff
@@ -207,19 +207,22 @@ export async function addWalletIdentity(walletItem: WalletTreeItem | IFabricWall
...
                     caUrl = connectionProfile.certificateAuthorities[showMoreCAs].url;
+                    caName = connectionProfile.certificateAuthorities[showMoreCAs].caName;
                 }
             } else {
                 caUrl = connectionProfile.certificateAuthorities[caKeys[0]].url;
+                caName = connectionProfile.certificateAuthorities[caKeys[0]].caName;
             }
 
-            const enrollment: { certificate: string, privateKey: string } = await certificateAuthority.enroll(caUrl, enrollmentID, enrollmentSecret);
+            const enrollment: { certificate: string, privateKey: string } = await certificateAuthority.enroll(caUrl, enrollmentID, enrollmentSecret, caName);
```
Comment (Jakeeyturner) [inline src/commands/addWalletIdentityCommand.ts]: Would it be possible to update the tests [here](https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/master/test/commands/addWalletIdentityCommand.test.ts) to check that `enroll` is being called with the `caName` as well?

Comment (mazyblue) [reply src/commands/addWalletIdentityCommand.ts]: Sure. I will try to add a test case and then update this pr.
