### PR TITLE
Error shown when no contracts to instantiate

### LINKED ISSUE #1702: Should error if no smart contracts to instantiate
## Description

`showChaincodeAndVersionQuickPick` doesn't check if there are 0 smart contracts to instantiate.
As a result, it's possible to get a prompt with no options.

We need to check for this and report that there are no smart contracts to instantiate.
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by au-shah**
closes #1702 
Signed-off-by: Akshat Shah <akshatshah@akshats-mbp.hursley.uk.ibm.com>

### CODE REVIEW

File: packages/blockchain-extension/extension/commands/UserInputUtil.ts [hunk 1]
```diff
@@ -425,7 +425,12 @@ export class UserInputUtil {
             placeHolder: prompt
         };
 
-        return await vscode.window.showQuickPick(quickPickItems, quickPickOptions);
+        if (quickPickItems.length === 0) {
+            throw new Error('No contracts found to instantiate');
```
Comment (lquintai) [inline packages/blockchain-extension/extension/commands/UserInputUtil.ts]: UserInputUtil.showChaincodeAndVersionQuickPick is also called from the upgrade command, so the error message shouldn't mention 'instantiate'. I think a generic 'No contracts found' should suffice.

Comment (au-shah) [reply packages/blockchain-extension/extension/commands/UserInputUtil.ts]: Yup, i agree
