### PR TITLE
Fix not being able to associate wallet identities with multiple environments

### LINKED ISSUE #2354: Associating wallet with multiple environments bug
## Description

In our v1.0.29/v1.0.30 release we accidentally introduced a bug whilst implementing the gateway & wallet icon changes.

To recreate:
- Create a SaaS/Cloud environment (env1)
- Create a new wallet (wallet1) and associate identities with env1
- Create another SaaS/Cloud environment (env2)
- Associate identities in wallet1 with env2
- Connecting will fail

To fix:
- Create/use a different wallet when creating a new environment

## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by erin-hughes**
Closes #2354 

Signed-off-by: Erin Hughes <Erin.Hughes@ibm.com>

### CODE REVIEW

File: packages/blockchain-extension/extension/commands/associateIdentityWithNode.ts [hunk 1]
```diff
@@ -150,9 +150,14 @@ export async function associateIdentityWithNode(replace: boolean = false, enviro
 
         await environment.updateNode(node);
 
-        if (!walletRegistryEntry.fromEnvironment && (environmentRegistryEntry.environmentType === EnvironmentType.OPS_TOOLS_ENVIRONMENT || environmentRegistryEntry.environmentType === EnvironmentType.SAAS_OPS_TOOLS_ENVIRONMENT)) {
-            walletRegistryEntry.fromEnvironment = environmentRegistryEntry.name;
+        if (!walletRegistryEntry.environmentGroups) {
+            walletRegistryEntry.environmentGroups = [environmentRegistryEntry.name];
             await FabricWalletRegistry.instance().update(walletRegistryEntry);
+        } else {
+            if (! walletRegistryEntry.environmentGroups.includes(environmentRegistryEntry.name)) {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/extension/commands/associateIdentityWithNode.ts:157]: Please could you remove the space between `!` and `walletRegistryEntry`

File: packages/blockchain-extension/extension/explorer/walletExplorer.ts [hunk 2]
```diff
@@ -72,43 +72,44 @@ export class BlockchainWalletExplorerProvider implements BlockchainExplorerProvi
...
-                if (walletRegistryEntry.fromEnvironment) {
-                    walletGroups.push([walletRegistryEntry]);
-                } else {
-                    otherWallets.push(walletRegistryEntry);
+        let walletRegistryEntries: FabricWalletRegistryEntry[] = await FabricWalletRegistry.instance().getAll();
+        const walletGroups: any[] = [];
+        const otherWallets: any[] = [];
+
+        let totalWallets: number = walletRegistryEntries.length;
+        while (0 < totalWallets) {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/extension/explorer/walletExplorer.ts:80]: Please could you comment this section - it's a bit tricky to follow

File: packages/blockchain-extension/extension/explorer/walletExplorer.ts [hunk 3]
```diff
@@ -130,21 +139,28 @@ export class BlockchainWalletExplorerProvider implements BlockchainExplorerProvi
         return tree;
     }
 
-    private async populateWallets(walletRegistryEntries: FabricWalletRegistryEntry[]): Promise<Array<WalletTreeItem>> {
-        const tree: Array<WalletTreeItem> = [];
+    private async populateWallets(walletRegistryEntries: any[]): Promise<Array<BlockchainTreeItem>> {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/extension/explorer/walletExplorer.ts:142]: Any reason for changing this to `any[]`?

File: packages/blockchain-extension/extension/explorer/walletExplorer.ts [hunk 4]
```diff
@@ -130,21 +139,28 @@ export class BlockchainWalletExplorerProvider implements BlockchainExplorerProvi
...
+        const tree: Array<BlockchainTreeItem> = [];
         for (const walletRegistryEntry of walletRegistryEntries) {
-            // get identityNames in the wallet
-            const walletGenerator: IFabricWalletGenerator = FabricWalletGeneratorFactory.getFabricWalletGenerator();
-            const wallet: IFabricWallet = await walletGenerator.getWallet(walletRegistryEntry);
-            const identityNames: string[] = await wallet.getIdentityNames();
+            // if we've got an array then it's a group of wallets, so push a WalletGroupTreeItem instead
+            if (walletRegistryEntry.length) {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/extension/explorer/walletExplorer.ts:146]: I'm assuming you're checking if 'walletRegistryEntry' is an array?
Probably best just calling `array. isArray()` if you want to do this.
If so, it probably doesn't make sense for these variables to be called `walletRegistryEntry` and `walletRegistryEntries`.
