### PR TITLE
Delete Multiple Environments

### LINKED ISSUE #1376: Remove multiple environments
## Description
At the moment, running `Delete Environment` from the Command Palette only allows you to select one environment to remove.
We should probably make this more consistent with Removing Packages, and allow a user to delete multiple at once.
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by toggle007**
Added functionality to delete multiple environments at once.
Closes #1376 

Signed-off-by: Akshat Shah <akshatshah@akshats-mbp.hursley.uk.ibm.com>

### CODE REVIEW

File: extension/commands/UserInputUtil.ts [hunk 1]
```diff
@@ -151,10 +151,12 @@ export class UserInputUtil {
...
         });
 
-        if (environmentsQuickPickItems.length === 1) {
-            return environmentsQuickPickItems[0];
-        } else if (environmentsQuickPickItems.length === 0) {
-            throw new Error('Error when choosing environment, no environments found to choose from.');
+        if (autoChoose) {
+            if (environmentsQuickPickItems.length === 1) {
+                return environmentsQuickPickItems[0];
+            } else if (environmentsQuickPickItems.length === 0) {
```
Comment (cazfletch) [inline extension/commands/UserInputUtil.ts]: the check to see if it found environments needs to be outside the auto choose

File: extension/commands/addGatewayCommand.ts [hunk 2]
```diff
@@ -43,7 +43,7 @@ export async function addGateway(): Promise<{} | void> {
         let gatewayName: string;
 
         if (gatewayMethod === UserInputUtil.ADD_GATEWAY_FROM_ENVIRONMENT) {
-            chosenEnvironment = await UserInputUtil.showFabricEnvironmentQuickPickBox('Choose an environment to create a gateway from', false);
+            chosenEnvironment = await UserInputUtil.showFabricEnvironmentQuickPickBox('Choose an environment to create a gateway from', false, false, true) as IBlockchainQuickPickItem<FabricEnvironmentRegistryEntry>;
```
Comment (cazfletch) [inline extension/commands/addGatewayCommand.ts]: the last argument should be false

File: extension/commands/importNodesToEnvironmentCommand.ts [hunk 3]
```diff
@@ -31,7 +31,7 @@ export async function importNodesToEnvironment(environmentRegistryEntry: FabricE
     try {
 
         if (!environmentRegistryEntry) {
-            const chosenEnvironment: IBlockchainQuickPickItem<FabricEnvironmentRegistryEntry> = await UserInputUtil.showFabricEnvironmentQuickPickBox('Choose an environment to import nodes to', false);
+            const chosenEnvironment: IBlockchainQuickPickItem<FabricEnvironmentRegistryEntry> = await UserInputUtil.showFabricEnvironmentQuickPickBox('Choose an environment to import nodes to', false, true, false) as IBlockchainQuickPickItem<FabricEnvironmentRegistryEntry>;
```
Comment (cazfletch) [inline extension/commands/importNodesToEnvironmentCommand.ts]: you don't need the last false here as its got a default value
