### PR TITLE
Fix debug when doing reload

### LINKED ISSUE #1230: Upgrade fails for Java contract with active debug session
## Description

Unexpected behaviour when trying to upgrade a contract, whilst running a debug session is active.

Found by @liam-grace 
## Expected Behavior

I'd expect to be asked for a name and version (or just a version if it can obtain the name) and then not error when upgrading.
## Actual Behavior

It errors when upgrading (check steps to reproduce)
## Steps to Reproduce

1. Install and instantiate a Java contract with name 'contract' and version '0.0.1' (from Open Project)
2. Start debug session with name 'contract' and version '0.0.2'
3. Try to upgrade smart contract
4. Straight to 'What function do you want to call?'
5. Smart contract with version 0.0.2 is already instantiated error

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by cazfletch**
Fixed problem with instantiate or upgrade wrongly being called when reload button is pressed

closes #1230

Signed-off-by: Caroline Fletcher <caroline.fletcher@uk.ibm.com>

### CODE REVIEW

File: src/debug/FabricDebugConfigurationProvider.ts [hunk 1]
```diff
@@ -30,6 +30,43 @@ export abstract class FabricDebugConfigurationProvider implements vscode.DebugCo
 
     private runtime: FabricRuntime;
 
+    public static async getInstantiatedVersion(chaincodeName: string): Promise<{ name: string, version: string }> {
```
Comment (Jakeeyturner) [inline src/debug/FabricDebugConfigurationProvider.ts]: Could we change the function name to `getInstantiatedChaincode` or something instead, as it returns the name as well as the version.

File: src/debug/FabricDebugConfigurationProvider.ts [hunk 2]
```diff
@@ -30,6 +30,43 @@ export abstract class FabricDebugConfigurationProvider implements vscode.DebugCo
...
+        // Determine what smart contracts are instantiated already
+        // Assume Local Fabric has one peer
+        const connection: IFabricEnvironmentConnection = await this.getConnection();
+        const allInstantiatedContracts: { name: string, version: string }[] = await connection.getAllInstantiatedChaincodes();
+        const smartContractVersionName: { name: string, version: string } = allInstantiatedContracts.find((contract: { name: string, version: string }) => {
```
Comment (Jakeeyturner) [inline src/debug/FabricDebugConfigurationProvider.ts]: Could we change `smartContractVersionName` to `smartContract` or something else
