### PR TITLE
Instantiate/Upgrade with smart contract EP (close #1603)

### LINKED ISSUE #1603: Smart contract endorsement policy
## Description

One feature of Fabric is the ability to pass a chaincode endorsement policy when instantiating/upgrading a smart contract.
This policy determines which peers endorsements are required for the smart contract.

In the extension, we should provide the ability to be able to pass in a chaincode endorsement policy when instantiating/upgrading.

More details about chaincode endorsement policies can be seen here - https://hyperledger-fabric.readthedocs.io/en/release-1.4/endorsement-policies.html 
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by Jakeeyturner**
Signed-off-by: Jake Turner <jaketurner25@live.com>

### CODE REVIEW

File: packages/blockchain-extension/extension/commands/instantiateCommand.ts [hunk 1]
```diff
@@ -186,6 +187,38 @@ export async function instantiateSmartContract(treeItem?: BlockchainTreeItem, ch
             }
         }
 
+        let chaincodeEP: any;
+        const wantsChaincodeEP: string = await UserInputUtil.showQuickPick('Enter a chaincode endorsement policy', [UserInputUtil.DEFAULT_CC_EP, UserInputUtil.CUSTOM]) as string;
```
Comment (cazfletch) [inline packages/blockchain-extension/extension/commands/instantiateCommand.ts]: Can we say smart contract not chaincode

Comment (Jakeeyturner) [reply packages/blockchain-extension/extension/commands/instantiateCommand.ts]: Changed!
