### PR TITLE
Setting to toggle Local Fabric functionality (close #1499)

### LINKED ISSUE #1499: Check Docker is installed for Local Fabric operations
## Description

As part of the epic #1497, before a user attempts to perform a Local Fabric operation, we should check that Docker & Docker Compose are installed first.

If Docker & Docker Compose aren't installed, we should probably throw an error and maybe even open the PreReq page.

## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by Jakeeyturner**
This PR introduces the user setting ibm-blockchain-platform.ext.enableLocalFabric to toggle the Local Fabric functionality on and off.
This PR is part of the epic #1497, so isn't complete. We still need to allow the user to toggle this from the pre-req page.

Signed-off-by: Jake Turner <jaketurner25@live.com>

### CODE REVIEW

File: extension/explorer/environmentExplorer.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ import { FabricEnvironment } from '../fabric/FabricEnvironment';
 import { EnvironmentConnectedTreeItem } from './runtimeOps/connectedTree/EnvironmentConnectedTreeItem';
 import { FabricChaincode } from '../fabric/FabricChaincode';
 import { TextTreeItem } from './model/TextTreeItem';
-
+import { ExtensionUtil } from '../util/ExtensionUtil';
 export class BlockchainEnvironmentExplorerProvider implements BlockchainExplorerProvider {
```
Comment (lquintai) [inline extension/explorer/environmentExplorer.ts]: Needs a blank line before the export.

File: extension/util/ExtensionUtil.ts [hunk 2]
```diff
@@ -392,6 +393,66 @@ export class ExtensionUtil {
             }
         }));
 
+        // Why were we ever doing a context.subscriptions.push() on this previously?
```
Comment (lquintai) [inline extension/util/ExtensionUtil.ts]: Do you want to leave this comment in?

File: test/TestUtil.ts [hunk 3]
```diff
@@ -113,6 +115,16 @@ export class TestUtil {
         await GlobalState.update(this.GLOBAL_STATE);
     }
 
+    static async storeEnableLocalFabric(): Promise<void> {
+        this.ENABLE_LOCAL_FABRIC = await vscode.workspace.getConfiguration().get(SettingConfigurations.EXTENSION_LOCAL_FABRIC);
+        console.log('Storing enable Local Fabric:', this.ENABLE_LOCAL_FABRIC);
```
Comment (lquintai) [inline test/TestUtil.ts]: Maybe change the message to 'Storing enable Local Fabric **to settings** ' to be similar to the restoring message.

File: packages/blockchain-extension/test/commands/UserInputUtil.test.ts [hunk 4]
```diff
@@ -322,6 +322,18 @@ describe('UserInputUtil', () => {
             result.label.should.equal('myGatewayB');
             result.data.should.deep.equal(gatewayEntryTwo);
         });
+
+        it('should throw an error if there are no gateways', async () => {
+            mySandBox.stub(gatewayRegistry, 'getAll').returns([]);
```
Comment (cazfletch) [inline packages/blockchain-extension/test/commands/UserInputUtil.test.ts]: can we just call `.clear()` rather than stubbing it

**Comment by cazfletch** [comment]
The web view doesn't update when you change the setting if you have it open so you end up out of sync
