### PR TITLE
Only export relevant wallet files

### LINKED ISSUE #2065: Exported wallets contain unexpected additional content
A wallet exported from the extension contains lots of additional files and directories that I do not expect to see in the wallet. Many of these are PEM files and other crypto content (not necessarily related to the wallet identities) and some look to be VS Code extension configuration files.

image

### PR DESCRIPTION
**Pull request by erin-hughes**
Closes #2065 

Signed-off-by: Erin Hughes <Erin.Hughes@ibm.com>

### CODE REVIEW

File: packages/blockchain-extension/extension/commands/exportWalletCommand.ts [hunk 1]
```diff
@@ -62,16 +62,42 @@ export async function exportWallet(walletTreeItem?: WalletTreeItem): Promise<voi
         return;
     }
 
-    // Copy the wallet to the chosen location
+    const walletName: string = exportedWalletRegistryEntry.displayName ? exportedWalletRegistryEntry.displayName : exportedWalletRegistryEntry.name;
+
     try {
-        await fs.copy(exportedWalletRegistryEntry.walletPath, walletUri.fsPath, { overwrite: true });
+        // create parent directory
+        await fs.mkdirp(walletUri.fsPath);
```
Comment (cazfletch) [inline packages/blockchain-extension/extension/commands/exportWalletCommand.ts:69]: if you use `fs.ensureDir` then it won't fail if it already exists

File: packages/blockchain-extension/extension/commands/exportWalletCommand.ts [hunk 2]
```diff
@@ -62,16 +62,42 @@ export async function exportWallet(walletTreeItem?: WalletTreeItem): Promise<voi
...
+        const walletContents: string[] = await fs.readdir(exportedWalletRegistryEntry.walletPath);
+
+        if (walletContents.length) {
+            for (const walletItem of walletContents) {
+                const walletItemPath: string = path.join(exportedWalletRegistryEntry.walletPath, walletItem);
+                // looking for directories that will contain identity information
+                if ((await fs.lstat(walletItemPath)).isDirectory()) {
+                    await fs.mkdirp(path.join(walletUri.fsPath, walletItem));
```
Comment (cazfletch) [inline packages/blockchain-extension/extension/commands/exportWalletCommand.ts:77]: again use `fs.ensureDir`
