### PR TITLE
Fixed telemetry events

### LINKED ISSUE #2050: Update environment connect telemetry
Now we have different types of environments we can connect to we should update the telemetry for connecting to an environment to show which type of environment a user is connecting to

### PR DESCRIPTION
**Pull request by au-shah**
closes #2050 
Signed-off-by: Akshat Shah <akshatshah@akshats-mbp.hursley.uk.ibm.com>

### CODE REVIEW

File: packages/blockchain-extension/extension/commands/environmentConnectCommand.ts [hunk 1]
```diff
@@ -119,8 +119,19 @@ export async function fabricEnvironmentConnect(fabricEnvironmentRegistryEntry: F
             environmentData = 'user environment';
         }
 
+        let envType: string;
+        if (fabricEnvironmentRegistryEntry.environmentType === EnvironmentType.ENVIRONMENT) {
```
Comment (Jakeeyturner) [inline packages/blockchain-extension/extension/commands/environmentConnectCommand.ts:123]: Could you comment in `FabricEnvironmentRegistryEntry.ts` (where we've defined the EnvironmentType enum), to state that if we update the enum, we need to update this part here as well, so it gets reported!

Comment (au-shah) [reply packages/blockchain-extension/extension/commands/environmentConnectCommand.ts:123]: Done! 👍
